services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - rMQ-data:/var/lib/rabbitmq
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - check_running
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  rMQ-data: {}
